# .github/FUNDING.yml

# GitHub Sponsors（如果你有開通 GitHub Sponsors）
github: [your-github-username]

# Ko-fi（最常用）
ko_fi: your-ko-fi-username

# 其他常見平台（可選，留空或刪除不想顯示的）
patreon: your-patreon-username
buy_me_a_coffee: your-bmac-username
custom: 
  - "https://paypal.me/yourpaypal"           # 自訂連結
  - "https://yourwebsite.com/donate"         # 自己的捐款頁面
